version: '3'

services:
    
    app:
        build:
            context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        command: node index.js
        networks:
            - work
        volumes:
            - ./node:/usr/src/app
        tty: true
        depends_on:
            - db
    
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - work
    
    nginx:
        build:
            context: nginx
        container_name: nginx
        networks:
            - work
        ports:
            - "8080:80"
        depends_on:
            - app

networks:
    work:
        driver: bridge